# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'

target 'Automoto' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Automoto
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'NVActivityIndicatorView'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
end
